### ISSUE TITLE
Uncaught Invariant Violation: SearchkitProvider.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

### ISSUE THREAD

**Issue by nirchernia** [searchkit/searchkit#286] opened 2016-05-25 17:57 UTC
I've been playing with the searchkit components and have been receiving errors regarding Searchkit Provider.render().

**Simple case of mine:**
```
import {
    SearchkitManager,
    SearchkitProvider,
    InitialLoader,
      ...
    } from "searchkit";

const InitialLoaderComponent = (props) => (
  <div className={props.bemBlocks.item().mix(props.bemBlocks.container("item"))}>
    loading please wait...
  </div>
)

class ConApp extends React.Component {

...

 render() {

    const searchKitManager = new SearchkitManager('setup-is-here')


    return (<SearchkitProvider searchkit={searchKitManager}>
            <InitialLoader component={InitialLoaderComponent}/>
        </SearchkitProvider>)
```

**Gives:** 

> Uncaught Invariant Violation: SearchkitProvider.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

**Another case:**

```

class ConApp extends React.Component {

...

 render() {

    const searchKitManager = new SearchkitManager('setup-is-here')


    return (<SearchkitProvider searchkit={searchKitManager}>
            <SearchBox />
        </SearchkitProvider>)
```

**Gives:**
> Uncaught Invariant Violation: SearchkitProvider.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

Aside from those, the only component that seems to work is `<Hits />`.  Any idea why these simple components are not working? And why `<Hits />` seems to work?

**Some notes:**
 -I am using es6, not tsx
 -I am not importing react or react-dom in THIS script directly
 -<Hits /> provides no styling even though styles are included (this might be default?)

**Comment by ssetem** [comment] 2016-05-25 18:01
@nirchernia a couple of things
- you should instantiate SearchkitManager outsde of the render method
- could you sanity check that all components are available (not undefined and imported correctly)

**Comment by nirchernia** [comment] 2016-05-25 18:13
@ssetem I have moved the SearchkitManager outside of the render. The results are the same though.

It looks like almost all (with the weird exception of `<Hits/>`) gives me that error.

**Comment by ssetem** [comment] 2016-05-25 18:14
I think its an import related issue where an element is undefined, could you console.log/debug whether all Searchkit components exist within your render method?

**Comment by nirchernia** [comment] 2016-05-25 18:18
After console.log-ing `<SearchBox />`:

![screen shot 2016-05-25 at 11 17 11 am](https://cloud.githubusercontent.com/assets/7181839/15551321/4c54fd06-226a-11e6-8c0a-499f27c9c7fc.png)

**Comment by ssetem** [comment] 2016-05-25 18:19
are you able to share a github repo? so I can take a look, its most likely import of react or search components as I have seen this same issue before

**Comment by nirchernia** [comment] 2016-05-25 18:32
Unfortunately I cannot share a full repo..I can say however that React is LIKELY the culprit.

I am running React 15.1.0  and React-dom15.1.0 and searchkit looks like it has dependencies of react-dom 14.8

I got that hint from npm ls | grep react
`npm ERR! extraneous: react-dom@0.14.8 /node_modules/searchkit/node_modules/react-dom`

When I set up searchkit, are you supposed to CD to the searchkit folder and run `npm install`? That might be causing the issue.

**Comment by ssetem** [comment] 2016-05-25 18:37
you shouldn;'t need too, but maybe you can continue investigating now you may know the cause.

If you continue to have issues, then make a simple repo with similar dep structure and we can then spend time to look on our side

Thanks!

**Comment by nirchernia** [comment] 2016-05-25 20:03
@ssetem 

After npm uninstalling and reinstalling searchkit the problem persists. Interestingly enough, react seems after including react (which I didnt do before) like this:
```

import * as React from "react";
import * as ReactDOM from "react-dom";
```

I get:

> Warning: Failed propType: Invalid prop `children` supplied to `SearchkitProvider`, expected a single ReactElement. Check the render method of `ConfidenceApp`.

Along with the other error. Any idea on the needs of searchkit in regards to react... is searchkit compatible with newer versions of react?

**Comment by ssetem** [comment] 2016-05-25 21:37
yep, the child of SearchkitProvider has to be single element, you could wrap what you have in a div tag etc

**Comment by nirchernia** [comment] 2016-05-26 16:13
@ssetem  Okay. I believe I am getting close to a solution. I have provided a gist with all my files interacting: https://gist.github.com/nirchernia/0340f7a0aa3c02cc3292e9b4a606d1de

I am getting the famous multiple reacts error _only_ when rendering/importing from searchkit:
> Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

I believe it is because searchkit has its own react dependency being loaded (looks like React 14.8.) and in my package.json I have specified React 15.1 

What is the proper way to set up my dependencies so that two aren't being loaded?

**Comment by ssetem** [comment] 2016-05-26 16:15
if your using webpack, you can create an alias.

**Comment by joemcelroy** [comment] 2016-05-26 16:27
searchkit-boilerplate uses react 15. https://github.com/searchkit/searchkit-boilerplate. Compare and see if you can spot the issue

**Comment by nirchernia** [comment] 2016-05-26 16:37
I'll try webpack.

@joemcelroy Hmm, I am using npm 2.15.1. I'll upgrade. Why the need for v3?

**Comment by ssetem** [comment] 2016-05-26 16:38
it handles transitive deps in flat way, plus its the latest :D

**Comment by nirchernia** [comment] 2016-05-27 15:05
Thanks for all the help @ssetem & @joemcelroy . It turns out that upgrading to NPMv3 and making my React dependency into a peer dependency allowed for the Multiple React versions to co-exist:

```
   "peerDependencies": {
    "react": "^15.1.0"
  },

```

You can close this issue, thanks again!

**Comment by ssetem** [comment] 2016-05-27 15:09
nice one!, @nirchernia  I'm going to close the issue if you don't mind, we can reopen if something crops  up

Thanks!

**Closed by ssetem** 2016-05-27 15:09 UTC

**Comment by devlesedi** [comment] 2016-06-04 09:07
I had the same _multiple copies of React_ error. Adding an alias, as @nirchernia suggested, solved the problem. For anyone having the same issue, add this to your webpack config file.
`resolve: {
    alias: {
      react: path.resolve('./node_modules/react')
    }`

**Comment by ssetem** [comment] 2016-06-04 12:37
thanks @devlesedi 

We should probably start a FAQ and add advice like this into it
